/*

 MARIO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 11

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define marioBank 0

/* Super Gameboy palette 0 */
#define marioSGBPal0c0 6076
#define marioSGBPal0c1 8935
#define marioSGBPal0c2 6596
#define marioSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define marioSGBPal1c0 6076
#define marioSGBPal1c1 8935
#define marioSGBPal1c2 6596
#define marioSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define marioSGBPal2c0 6076
#define marioSGBPal2c1 8935
#define marioSGBPal2c2 6596
#define marioSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define marioSGBPal3c0 6076
#define marioSGBPal3c1 8935
#define marioSGBPal3c2 6596
#define marioSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define marioCGBPal0c0 6076
#define marioCGBPal0c1 8935
#define marioCGBPal0c2 6596
#define marioCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define marioCGBPal1c0 6076
#define marioCGBPal1c1 2783
#define marioCGBPal1c2 6574
#define marioCGBPal1c3 27

/* Gameboy Color palette 2 */
#define marioCGBPal2c0 6076
#define marioCGBPal2c1 2783
#define marioCGBPal2c2 6574
#define marioCGBPal2c3 704

/* Gameboy Color palette 3 */
#define marioCGBPal3c0 32555
#define marioCGBPal3c1 20255
#define marioCGBPal3c2 307
#define marioCGBPal3c3 0

/* Gameboy Color palette 4 */
#define marioCGBPal4c0 6076
#define marioCGBPal4c1 20223
#define marioCGBPal4c2 307
#define marioCGBPal4c3 0

/* Gameboy Color palette 5 */
#define marioCGBPal5c0 6076
#define marioCGBPal5c1 8935
#define marioCGBPal5c2 6596
#define marioCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define marioCGBPal6c0 6076
#define marioCGBPal6c1 8935
#define marioCGBPal6c2 6596
#define marioCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define marioCGBPal7c0 6076
#define marioCGBPal7c1 8935
#define marioCGBPal7c2 6596
#define marioCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char marioCGB[];
/* Start of tile array. */
extern unsigned char mario[];

/* End of MARIO.H */
