/*

 MARIO-BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : C:\Users\Administrator\Downloads\backgound.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define marioBGWidth 32
#define marioBGHeight 18
#define marioBGBank 0

#define marioBG marioBGPLN0
extern unsigned char marioBGPLN0[];
extern unsigned char marioBGPLN1[];

/* End of MARIO-BG.H */
