/*

 MARIO-BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\Administrator\Downloads\backgound.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define marioBgWidth 20
#define marioBgHeight 18
#define marioBgBank 0

#define marioBg marioBgPLN0
extern unsigned char marioBgPLN0[];
extern unsigned char marioBgPLN1[];

/* End of MARIO-BG.H */
