/*

 MARIO_BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Develop\GameboyProject\gb5\backgound.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define marioBgWidth 20
#define marioBgHeight 18
#define marioBgBank 0

extern unsigned char marioBg[];

/* End of MARIO_BG.H */
